
services:
  productos:
    build: ./microservicio-productos
    ports:
      - "3306:3306"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: farmacia
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: